version: "3.9"
services:
  php-apache:
    build:
      context: .
      dockerfile: php.dockerfile
    image: php:7.4-apache
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
    links:
      - mariadb
    volumes:
      - ./src/public:/var/www/html/
      - ./src/Modules:/var/php/Modules/
      - ./src/Templates:/var/php/Templates/
      - ./src/config:/var/php/config/
    networks:
      vpcbr:
        ipv4_address: 172.19.0.2

  phpunit:
    build:
      context: .
      dockerfile: phpunit.dockerfile
    image: php:7.4.19-cli
    restart: never
    depends_on:
      - "mariadb"
    links:
      - mariadb
    volumes:
      - .:/var/php/
    working_dir: /var/php/
    entrypoint: vendor/bin/phpunit
    networks:
      vpcbr:
        ipv4_address: 172.19.0.4


  mariadb:
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: blog
    ports:
      - "8889:3306"
    networks:
      vpcbr:
        ipv4_address: 172.19.0.3

volumes:
  mariadb:

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
